### ISSUE TITLE
sim does not start - error msg

### ISSUE THREAD

**Issue by danielemarinazzo** [shlizee/C-elegans-Neural-Interactome#2]
Hi

first of all thanks for this really promising tool!

I installed the tool on Windows 10, following the instructions.
I manage to start the Interactome in the browser, but when I press play the "wait" bars appear, and they just stay there. In the meantime I have some messages on my command prompt, ending with an error message. Here pasted below.

Thanks in advance for your help!

(C:\Users\dmarinaz\Anaconda2) C:\Users\dmarinaz\Documents\Python Scripts\C-elegans-Neural-Interactome-master>python initialize.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 682-608-387
(19096) wsgi starting up on http://0.0.0.0:5000
(19096) accepted ('127.0.0.1', 55867)
127.0.0.1 - - [06/Feb/2019 21:31:09] "GET / HTTP/1.1" 200 7507 0.020000
127.0.0.1 - - [06/Feb/2019 21:31:10] "GET /socket.io/?EIO=3&transport=polling&t=MZ4WTYn HTTP/1.1" 200 381 0.000000
127.0.0.1 - - [06/Feb/2019 21:31:10] "POST /socket.io/?EIO=3&transport=polling&t=MZ4WTaj&sid=3e85014300aa4f20a17c1b6d6252ce44 HTTP/1.1" 200 219 0.007000
(19096) accepted ('127.0.0.1', 55869)
(19096) accepted ('127.0.0.1', 55870)
127.0.0.1 - - [06/Feb/2019 21:31:10] "GET /socket.io/?EIO=3&transport=polling&t=MZ4WTan&sid=3e85014300aa4f20a17c1b6d6252ce44 HTTP/1.1" 200 23852 0.044000
message handler error
Traceback (most recent call last):
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\engineio\server.py", line 505, in _trigger_event
    return self.handlers[event](*args)
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\socketio\server.py", line 590, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\socketio\server.py", line 526, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\socketio\server.py", line 529, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\socketio\server.py", line 558, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\flask_socketio\__init__.py", line 258, in _handler
    *args)
  File "C:\Users\dmarinaz\Anaconda2\lib\site-packages\flask_socketio\__init__.py", line 641, in _handle_event
    ret = handler(*args)
  File "initialize.py", line 357, in startRun
    run_Network(t_Delta, atol)
  File "initialize.py", line 253, in run_Network
    oldMask = newMask.copy()
NameError: global name 'newMask' is not defined

**Comment by jimin9292** [comment]
Did you set some stimulus (in the panel of neurons on the left) before pressing play? 
This error appears when the function that sets up the simulation fails to locate the initial stimulus and since no other errors were logged it seems like it is due to no input being defined.

I just pushed the new version to the Github which should fix this issue such that if you didn’t set any stimulus in the beginning, it will just set inputs to all neurons to zero. However, in order to get some dynamics an input should be chosen.

You can set which neurons receive inputs and the amplitude of the input by clicking a neuron on the lefthand panel. A default stimulus of 5.0 nA will be set as external current into that neuron. You can then adjust the amplitude through scrollable white bar in the range of 0 nA to 10 nA.

**Comment by danielemarinazzo** [comment]
Thanks a lot for the prompt reply. It works now indeed! And thanks for updating to a foolproof version :)
